apiVersion: v1
kind: Service
metadata:
  name: basic-kubernetes-service
spec:
  selector:
    app: basic-kubernetes-app
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 5000
  type: LoadBalancer
