name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3


    - name: Debug Secrets
      run: |
         echo "DOCKER_USERNAME is: ${{ secrets.DOCKER_USERNAME }}" echo "DOCKER_PASSWORD is: ${{ secrets.DOCKER_PASSWORD }}"

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      secrets: inherit

    - name: Build Docker Image
      run: |
        docker build -t emrekardaslar/basic-kubernetes-app:latest .

    - name: Push Docker Image
      run: |
        docker push emrekardaslar/basic-kubernetes-app:latest

    - name: Deploy to Kubernetes
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        kubectl set image deployment/basic-kubernetes-app \
          basic-kubernetes-app=emrekardaslar/basic-kubernetes-app:latest -n default
        kubectl rollout restart deployment/basic-kubernetes-app -n default
